"use client";

export default function KnowledgePage() {
  return (
    <div className="p-6">
      <div className="mb-6">
        <h1 className="text-lg font-medium text-foreground">Knowledge</h1>
        <p className="mt-1 text-xs text-text-quaternary">
          Knowledge base synced from your GitHub repos. Knowledge entries are generated by agents and curated for reuse.
        </p>
      </div>

      <div className="flex h-40 items-center justify-center rounded-lg border border-dashed border-border">
        <div className="text-center">
          <p className="text-sm text-text-tertiary">Knowledge management coming soon</p>
          <p className="mt-1 text-xs text-text-quaternary">
            Knowledge is stored in your {"{prefix}"}-knowledge GitHub repo and synced via HermesLoop
          </p>
        </div>
      </div>
    </div>
  );
}
